In [1]:
import pandas as pd
import boto3
import os

In [2]:
file_names = [f for f in os.listdir('../src/data') if '_v10_' in f]
sorted(file_names)

['final_wide_df_v10_0.parquet',
 'final_wide_df_v10_1.parquet',
 'final_wide_df_v10_10.parquet',
 'final_wide_df_v10_11.parquet',
 'final_wide_df_v10_12.parquet',
 'final_wide_df_v10_13.parquet',
 'final_wide_df_v10_15.parquet',
 'final_wide_df_v10_16.parquet',
 'final_wide_df_v10_17.parquet',
 'final_wide_df_v10_18.parquet',
 'final_wide_df_v10_19.parquet',
 'final_wide_df_v10_2.parquet',
 'final_wide_df_v10_20.parquet',
 'final_wide_df_v10_21.parquet',
 'final_wide_df_v10_22.parquet',
 'final_wide_df_v10_23.parquet',
 'final_wide_df_v10_24.parquet',
 'final_wide_df_v10_25.parquet',
 'final_wide_df_v10_26.parquet',
 'final_wide_df_v10_27.parquet',
 'final_wide_df_v10_28.parquet',
 'final_wide_df_v10_29.parquet',
 'final_wide_df_v10_3.parquet',
 'final_wide_df_v10_30.parquet',
 'final_wide_df_v10_31.parquet',
 'final_wide_df_v10_32.parquet',
 'final_wide_df_v10_33.parquet',
 'final_wide_df_v10_34.parquet',
 'final_wide_df_v10_35.parquet',
 'final_wide_df_v10_36.parquet',
 'final_wide_df_v10_37.parquet',
 'final_wide_df_v10_38.parquet',
 'final_wide_df_v10_39.parquet',
 'final_wide_df_v10_4.parquet',
 'final_wide_df_v10_5.parquet',
 'final_wide_df_v10_6.parquet',
 'final_wide_df_v10_7.parquet',
 'final_wide_df_v10_8.parquet',
 'final_wide_df_v10_9.parquet']

In [3]:
dfs = [pd.read_parquet('../src/data/'+fn) for fn in file_names]

In [4]:
df = pd.concat(dfs)

In [5]:
df.head()

,ip_ddos_span_0,er_ddos_span_0,out_ddos_span_0,snf_ddos_span_0,icf_ddos_span_0,hh_ddos_span_0,amb_ddos_span_0,hsp_ddos_span_0,pro_ddos_span_0,spc_fac_ddos_span_0,...,is_group_13.0,is_group_17.0,is_group_9.0,is_group_21.0,is_group_18.0,is_male,age,member_id,target,period
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,68.0,1.0,12427.34,23
1,0.0,0.0,0.0,36.0,0.0,0.0,2.0,0.0,62.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,90.0,2.0,419.98,23
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,60.0,3.0,0.00,23
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,41.0,6.0,0.00,23
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,55.0,8.0,0.00,23

In [6]:
df.shape

(1385247, 1562)

In [8]:
df.to_parquet('./modeling_latest/master_wide_df_v10.parquet')

In [10]:
df.to_csv('v10.csv', index=False)

In [10]:
s3_client = boto3.client('s3')
response = s3_client.upload_file('./modeling_latest/master_wide_df_v10.parquet', 'cb-analytics-exports-us-east-2-prd', 'sagemaker/training_data/master_wide_df_v10.parquet')